name: Github Actions for Pressio

on: [push]

jobs:
  build:

    runs-on: ubuntu-20.04
    strategy:
      matrix:
          config:
#           - {
#               name: "Ubuntu Latest GCC",
#               build_type: "Debug", cc: "gcc", cxx: "g++",
#               options: "-eigen-path=/home/runner/work/pressio/pressio_builds/eigen/install -gtest-path=/home/runner/work/pressio/pressio_builds/gtest/install",
#               envscript: "",
#               requirements: ""
#             }
#           - {
#               name: "Ubuntu Latest Clang",
#               build_type: "Debug", cc: "clang", cxx: "clang++",
#               options: "-eigen-path=/home/runner/work/pressio/pressio_builds/eigen/install -gtest-path=/home/runner/work/pressio/pressio_builds/gtest/install",
#               envscript: "",
#               requirements: ""
#             }
          - {
              name: "Ubuntu Latest MPI - trilinos",
              build_type: "Debug", cc: "mpicc", cxx: "mpicxx",
              options: "-cmake-generator-name=default_mpi_trilinos_with_tests -eigen-path=/home/runner/work/pressio/pressio_builds/eigen/install -gtest-path=/home/runner/work/pressio/pressio_builds/gtest/install -trilinos-path=/home/runner/work/pressio/pressio_builds/trilinos/install",
              envscript: "-env-script=/home/runner/work/pressio/pressio_repos/pressio-builder/sample_env_scripts/ubuntu-env-script.sh",
              requirements: "sudo apt install -y openmpi-bin libopenmpi-dev"
            }

    steps:
    - uses: actions/checkout@v1
    - name: Creating environnement...
      run: |
        cd ..
        mkdir pressio_repos
        PARENT_DIR=$(pwd)
        echo ::set-env name=WORKSPACE_PARENT_DIR::$PARENT_DIR
        echo ::set-env name=PRESSIO_REPOS::$PARENT_DIR/pressio_repos
        echo ::set-env name=PRESSIO_BUILDS::$PARENT_DIR/pressio_builds
        ${{ matrix.config.requirements }}
        ls /usr/lib/x86_64-linux-gnu/libmpi*
        gcc --version
        mpic++ -showme:version
        whereis libmpi.so
    - name: Cloning Pressio Builder...
      run: |
        cd ${{ env.PRESSIO_REPOS }}
        git clone git://github.com/Pressio/pressio-builder.git
        cd pressio-builder
        git checkout master
    - name: Get TPLs...
      run: |
        export TERM=xterm
        echo $TERM
        docker run -di perrinel/ubuntu-pressio-tpl
        TNAME=$(docker ps --format "{{.Names}}")
        echo $TNAME
        docker cp $TNAME:/home/pressio_builds ${{ env.WORKSPACE_PARENT_DIR }}
        docker cp $TNAME:/home/pressio_repos/pressio-builder/sample_env_scripts/ubuntu-env-script.sh ${{ env.PRESSIO_REPOS }}/pressio-builder/sample_env_scripts/
    - name: Run main_pressio script
      env:
        CC: ${{ matrix.config.cc }}
        CXX: ${{ matrix.config.cxx }}
      run: |
        export TERM=xterm
        cd ${{ env.PRESSIO_REPOS }}/pressio-builder
        ./main_pressio.sh ${{ matrix.config.envscript }} -dryrun=no -pressio-src=${{ env.WORKSPACE_PARENT_DIR }}/pressio -target-dir=${{ env.PRESSIO_BUILDS }} -cmake-generator-name=default_with_tests ${{ matrix.config.options }}
    - name: Run CTest
      run: |
        cd ${{ env.PRESSIO_BUILDS }}/pressio/build
        ctest -V
